{% set name = "docker-cli" %}
{% set version = "27.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/cli/archive/v{{ version }}.tar.gz
  sha256: 84db222b6d65695f3d8ae02acf8f21d90fb3f2169754bb94d314864c37bac7f3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ stdlib('c') }}
    - go-licenses
    - go-md2man  # [unix]

test:
  commands:
    - docker --help

about:
  home: https://github.com/docker/cli
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  dev_url: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
