{% set name = "docker-cli" %}
{% set version = "27.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/cli/archive/v{{ version }}.tar.gz
  sha256: abd601fcf2223a550a9a8ef9117345f932b06ccb084bbfb8d111f6809d5e6c83

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ stdlib('c') }}
    - go-licenses
    - go-md2man  # [unix]

test:
  commands:
    - docker --help

about:
  home: https://github.com/docker/cli
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  dev_url: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
