context:
  version: "28.0.4"

package:
  name: docker-cli
  version: ${{ version }}

source:
  url: https://github.com/docker/cli/archive/v${{ version }}.tar.gz
  sha256: 09b41aa5ff656bc135feb80cb9b73c70aeba099ef9756c3cef7bcb2eb3c98ba6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses
    - if: unix
      then: go-md2man

tests:
  - script:
      - docker --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  homepage: https://github.com/docker/cli
  repository: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
