context:
  version: "29.8.0"

package:
  name: docker-cli
  version: ${{ version }}

source:
  url: https://github.com/docker/cli/archive/v${{ version }}.tar.gz
  sha256: c5fadbc00c02dbecb1b7c9936e188baf9c80421a9107e7e9ad36a0923a0fc764

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses
    - if: unix
      then:
        - go-md2man
        - sed
      else: m2-sed
tests:
  - script:
      - docker --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  homepage: https://github.com/docker/cli
  repository: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
