context:
  version: "28.0.1"

package:
  name: docker-cli
  version: ${{ version }}

source:
  url: https://github.com/docker/cli/archive/v${{ version }}.tar.gz
  sha256: d7495aa47f52e5ba5b16d6ffbc07678cbf496b9f00206c5918f936206ad986f5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses
    - if: unix
      then: go-md2man

tests:
  - script:
      - docker --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  homepage: https://github.com/docker/cli
  repository: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
